- name: "[Play 1] Put some lode on the CPUs"
  hosts: all
  become: true 
  tasks:

  - name: "Put some lode on the CPUs"
    command: yes > /dev/null &
    with_sequence: start=1 end={{ansible_processor_vcpus|int}}
