- name: "[Play 1] Put some lode on the CPUs"
  hosts: all
  become: true
  tasks:

  - name: "Install psmisc package"
    package:
      name: psmisc
      state: installed
      
  - name: "Put some lode on the CPUs"
    shell: "(cd /; /usr/bin/yes > /dev/null 2>&1 &)"
    async: 10
    poll: 0
    with_sequence: start=1 end={{ansible_processor_vcpus|int}}
