- name: "[Play 1] Create new vm from template"
  hosts: localhost
  gather_facts: false
  vars:
    parallels_hypervisor:
    vm_name:
    vm_cpu:
    vm_memory:
    vm_template:

  tasks:
  - include_role:
      name: ansible-role-parallels-vm
      apply:
       delegate_to: "{{ parallels_hypervisor }}"
    vars:
      parallels_vm_name: "{{ vm_name }}"
      parallels_vm_memory: "{{ vm_memory }}"
      parallels_vm_cpu_count: "{{ vm_cpu }}"
      parallels_vm_state: running
      parallels_vm_clone: True
      parallels_vm_template: "{{ vm_template }}"

  - name: Setup in-memory inventory
    add_host:
      name: "{{ vm_name }}"
      groups:
        - just_created_vms

- name: "[Play 2] Post Configuration of VM"
  hosts: just_created_vms
  become: true
  vars:
  tasks:

  - name: test
    command: ls
